### ISSUE TITLE
Question about the installing using the index.md

### ISSUE THREAD

**Issue by Letssharearow** [davidsmorais/kuro#26]
I am trying to install this program to use Microsoft To do on my Ubuntu System (I am new to Linux)
The index.md instructs me to "simply run yarn release". Do I have to run this in the Terminal like the other instructions? Because this gives me an Error. 
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'release'`

"yarn release.nix" which actually finds the file doesn't seem to know what to do with # icons and # desktop ...
`00h00m00s 0/0: : ERROR: Syntax error: unknown step: # icons`

**How did you set up this system and how do you run the application?**

**Comment by davidsmorais** [comment]
Hey  @Letssharearow 👋 
You don't need to clone and build the repo in order to install the application in Ubuntu.

You just need to head to the [releases](https://github.com/davidsmorais/kuro/releases) page and download either `deb`, `AppImage` or `snap` format.
If you're new to Linux, I suggest you try the [deb package ⬇️](https://github.com/davidsmorais/kuro/releases/download/v8.0.4a/kuro_8.0.4-a_amd64.deb) as it has the built in GUI for installing packages in Ubuntu 👍
