### ISSUE TITLE
[Bug 🐞]: Office 365 Company Login not possible

### ISSUE THREAD

**Issue by tomturbu** [davidsmorais/kuro#60]
# Office 365 Corporate Login not possible

**Describe the bug**
Using Office 365 with a corporate account, that means the login will be redirected to corporate login page. The company login page can't be loaded and a blank screen is shown.

**Reproduction Steps**
Login with a company account, which is using corporate login. The corporate login page can't be displayed because the url which gets loaded contains some kuno parts, i.e.:

https://my-company-login-page.com/opt/Kuro/resources/app.asar/node_modules/conf/node_modules/ajv/dist/vocabularies/applicator/properties.js.map

**Expected Behavior**
Corporate Login page should be displayed, so i can login with corporate id

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34303196/197146228-6b0e08c6-9252-4ca4-91cc-70495903494c.png)

**Technical Info (please complete the following information)**
 - OS: PopOS 22.04 LTS
 - Kuro Version: 8.1.5

**Additional context**
can be reproduced also on Ubuntu and Fedora

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hey @tomturbu :wave: 
Thanks for reporting this. I'll deal with this as soon as I can with top priority.

I know To-Do recently had a big update, just hoping this is the only instance in which the URL redirect is bugged :pray:

**Comment by davidsmorais** [comment]
@tomturbu was investigating this, and it doesn't seem to be an issue with Kuro.

Those warnings you are getting are only the original source map not being available for Electron apps. You can read more about this issue [here](https://github.com/electron/electron/issues/22996). You can retrieve the current 

I really don't have an Office365 account anymore that I can use to investigate further. Can you print `window.location` and check if the URL is properly parsed ? 

Also, can you please check for console for errors only ?
![image](https://user-images.githubusercontent.com/22729436/199617742-f7584281-18e1-485e-aaf3-79d2ad814f47.png)


I'm guessing this is some kind of security issue since Kuro is essentially opened inside an electron container, but would like to see if there's an option to fix this

**Comment by tomturbu** [comment]
@davidsmorais hey, i have no clue, but with latest version it works as expected.

After typing in my company-account, i get redirected to company login-page - then i have to login with company-account, password and otp, and after that i get redirected to todo... so all as expected....

I'll close this issue.
